import Head from "next/head";
import styles from "../styles/pages/Home.module.scss";

import { FiPlusCircle } from "react-icons/fi";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bank | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainer}>
        <div className={styles.limiter}>
          <section className={styles.highlight}>
            <aside>
              <p>
                Inovação, Design e <strong>Experiência</strong>
              </p>
              <span>sempre a frente em soluções digitais</span>

              <button type="button">Saiba mais</button>
            </aside>
            <div>
              <img
                draggable={false}
                src="/assets/digital-image.svg"
                alt="10 Bank - innovation"
              />
            </div>
          </section>

          <div className={styles.about}>
            <h2>Sobre nós</h2>

            <div>
              <aside>
                <img
                  draggable={false}
                  src="/assets/about-img.png"
                  alt="About us"
                />
              </aside>
              <div>
                <h4>Qual o seu próximo projeto?</h4>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  specimen book. It has survived not only five centuries, but
                  also the leap into electronic typesetting, remaining
                  essentially unchanged.
                </p>

                <button type="button">Download CV</button>
              </div>
            </div>
          </div>

          <div className={styles.services}>
            <h3>Serviços</h3>
            <h2>Proporcionamos uma melhor experiência</h2>

            <div>
              <aside>
                <div>
                  <h1>85%</h1>
                  <div className={styles.loadingBar}>
                    <div></div>
                  </div>
                  <h4>Design UI</h4>
                  <p>Photoshop, Illustrator</p>
                </div>
              </aside>
              <div>
                <div>
                  <img draggable={false} src="/assets/tools.svg" alt="tools" />
                </div>

                <h4>Design</h4>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  specimen book.
                </p>

                <button type="button">Saiba mais</button>
              </div>
            </div>
          </div>

          <div className={styles.portfolio}>
            <h3>Portfolio</h3>
            <h2>Meus trabalhos</h2>

            <div>
              <div>
                <div className={styles.lock}>
                  <p>phone Markup</p>
                  <FiPlusCircle />
                </div>

                <img src="/assets/port-a.png" alt="portfolio A" />
              </div>
              <div>
                <div className={styles.lock}>
                  <p>phone Markup</p>
                  <FiPlusCircle />
                </div>
                <img src="/assets/port-a.png" alt="portfolio A" />
              </div>
              <div>
                <div className={styles.lock}>
                  <p>phone Markup</p>
                  <FiPlusCircle />
                </div>
                <img src="/assets/port-a.png" alt="portfolio A" />
              </div>
              <div>
                <div className={styles.lock}>
                  <p>phone Markup</p>
                  <FiPlusCircle />
                </div>
                <img src="/assets/port-a.png" alt="portfolio A" />
              </div>
            </div>
          </div>

          <div className={styles.feedback}>
            <h3>Contato</h3>
            <h2>Envie sua mensagem</h2>

            <form>
              <input type="text" placeholder="Nome" required />

              <div>
                <input type="text" placeholder="Telefone" required />
                <input type="email" placeholder="E-mail" required />
              </div>

              <textarea
                name="mensagem"
                id="mensagem"
                placeholder="mensagem"
                cols={30}
                rows={10}
              ></textarea>

              <button type="submit">Enviar</button>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
